function geraBg() {
    // Tipo de Local
    listaDescLocal = ["uma Cidade", "um Ducado", "uma Vila", "um Vilarejo", "um reino"];
    local = listaDescLocal[(Math.random() * listaDescLocal.length) | 0];
    
    listaPrefixLocalMasc = ["Abismo","Alto","Amor","Amuleto","Anel","Apiário","Arco","Ártico","Arvoredo","Barranco","Bastião","Bosque","Brejo","Brilho","Buraco","Burgo","Cáis","Cálice","Caminho","Campanário","Campo","Carvalho","Castelo","Cavaleiro","Cedro","Cemitério","Céu","Condado","Coração","Córrego","Cristal","Cultivo","Declíneo","Declive ","Desastre","Deserto","Diamante","Domínio","Ducado","Elo","Escudo","Espaço","Estreito","Farol","Festim","Festival","Forte","Fosso","Fragmento","Gramado","Horizonte","Jardim","Lago","Lamaçal","Lar","Litoral","Machado","Mar","Mirante","Moínho","Monastério","Morro","Muro","Ninho","Olhar","Olho","Origem","Osso","Ouro","Pântano","Passo","Pensamento","Perfume","Pico","Píer","Pinheiro","Planalto","Poder","Poema","Poleiro","Pomar","Pomo","Porto","Posto","Precipício","Presa","Recanto","Rio","Rochedo","Rubi","Salão","Santuário","Senado","Sentimento","Sino","Solo","Souto","Terremoto","Terreno","Topo","Tornado","Totem","Trevo","Tribunal","Trono","Vale","Veio","Vinhedo","Limoeiro","Lírio","Arbusto","Bambu","Cacto","Cipó","Poço"];
    listaSufixLocalMasc = ["Alado","Alegre","Ancião","Antigo","Arcano","Ascendente","Avermelhado","Azul","Azulado","Branco","Caído","Caloroso","Celeste","Chuvoso","Cinzento","Congelado","da Alegria","da Alma","da Alvorada","da Chuva","da Colheita","da Coragem","da Disparidade","da Dor","da Escuridão","da Eternidade","da Felicidade","da Ganância","da Geada","da Graça","da Gula","da Honra","da Inveja","da Ira","da Justiça","da Lealdade","da Luxúria","da Luz","da Luz Solar","da Madrugada","da Magia","da Maldição","da Morte","da Neblina","da Nevasca","da Noite","da Ordem","da Pecadora","da Penumbra","da Perturbação","da Pobreza","da Podridão","da Prata","da Preguiça","da Primavera","da Raposa","da Salamandra","da Serenidade","da Serpe","da Serpente","da Tempestade","da Tristeza","da Vida","das Chamas","das Cinzas","das Estrelas","das Joias","de Ninguém","Demoníaco","Desbotado","Distante","do Além","do Amanhecer","do Anoitecer","do Berserker","do Brilho da Lua","do Brilho Solar","do Corvo","do Desalento","do Dever","do Dragão","do Fiasco","do Fim","do Hierarca","do Homicida","do Imperdoável","do Inverno","do Lamento","do Leão","do Leste","do Lorde","do Monarca","do Norte","do Oeste","do Orgulho","do Orvalho","do Ouro","do Outono","do Pecado","do Pecador","do Repouso","do Risonho","do Sofrimento","do Solstício","do Sul","do Trigre","do Urso","do Vazio","do Vento","do Verão","dos Cristais","dos Deuses","dos Heróis","dos Tolos","Dracônico"];
   
    listaPrefixLocalFem = ["Adaga","Aposta","Areia","Árvore","Ascenção","Baía","Baixada","Beirada","Benção","Borda","Cachoeira","Capela","Catacumba","Cavaleira","Caveira","Caverna","Cerejeira","Chama","Chegada","Cicatriz","Clareira","Colina","Colméia","Constelação","Contenda","Cordilheira","Coroa","Corrente","Côrte","Cratera","Dança","Dobra","Doca","Elevação","Encruzilhada","Esfera","Espada","Estrada","Estrela","Extremidade","Fazenda","Fenda","Festa","Flecha","Flor","Floresta","Fogueira","Folha","Forja","Fortaleza","Gruta","Guarita","Lagoa","Lâmina","Lança","Luz","Madeira","Madrugada","Masmorra","Mata","Mina","Moeda","Montanha","Muralha","Nascente","Neblina","Névoa","Noite","Origem","Orquídea","Partida","Passagem","Pedra","Pena","Pétala","Planície","Plantação","Pluma","Poção","Poeira","Poesia","Ponte","Praia","Prelúdio","Presa","Prisão","Quebra","Queda","Raíz","Ravina","Rio","Rocha","Rosa","Ruína","Santa","Semente","Subida","Tenda","Terra","Toca","Torre","Travessia","Trilha","Via","Vigília","Visão","Depressão","Amoreira","Pimenta","Poça","Bacia","Alcova"];
    listaSufixLocalFem = ["Alegre","Alada","Anciã","Antiga","Arcana","Ascendente","Avermelhada","Azul","Azulada","Branca","Caída","Calorosa","Celeste","Chuvosa","Cinzenta","Congelada","da Alegria","da Alma","da Alvorada","da Chuva","da Colheita","da Coragem","da Disparidade","da Dor","da Escuridão","da Eternidade","da Felicidade","da Fumaça","da Ganância","da Geada","da Graça","da Gula","da Honra","da Inveja","da Ira","da Justiça","da Lealdade","da Luxúria","da Luz","da Luz Solar","da Magia","da Maldição","da Mentira","da Morte","da Neblina","da Nevasca","da Ordem","da Pecadora","da Penumbra","da Perturbação","da Pobreza","da Podridão","da Prata","da Preguiça","da Primavera","da Raposa","da Salamandra","da Serenidade","da Serpe","da Serpente","da Tempestade","da Tristeza","da Vida","das Chamas","das Cinzas","das Estrelas","das Joias","de Ninguém","Demoníaca","Desbotada","Distante","do Além","do Amanhecer","do Anoitecer","do Berserker","do Brilho da Lua","do Brilho Solar","do Corvo","do Desalento","do Dever","do Dragão","do Fiasco","do Fim","do Hierarca","do Homicida","do Imperdoável","do Inverno","do Lamento","do Leão","do Leste","do Lorde","do Monarca","do Norte","do Nunca","do Oeste","do Orgulho","do Orvalho","do Ouro","do Outono","do Pecado","do Pecador","do Repouso","do Risonho","do Sofrimento","do Sol Nascente","do Sul","do Trigre","do Urso","do Vento","do Verão","dos Cristais","dos Deuses","dos Heróis","dos Tolos","Dracônica","Escarlate","Escura","Esquecida","Esverdeada","Eterna","Fantasma","Flamejante","Fúnebre","Furiosa","Grande","Lamuriosa","Laranja","Lendária","Límpida","Lírica","Lunar","Média","Mística","Negra","Neutra","Nova","Nula","Obscura","Ocidental","Oriental","Pegajosa","Pequena","Perdida","Poderosa","Primordial","Profunda","Púrpura","Quebrada","Queimada","Radiante","Reluzente","Retorcida","Rochosa","Sagrada","Sangrenta","Santa","Seca","Selvagem","Silenciosa","Solar","Solitária","Sombria","Tempestuosa","Turbulenta","Vazia","Venenosa","Verde","Vermelha","Violenta","Violeta","Vívida"];

    // Nome do Local
    prefixLocalMasc = listaPrefixLocalMasc[(Math.random() * listaPrefixLocalMasc.length) | 0];
    sufixLocalMasc = listaSufixLocalMasc[(Math.random() * listaSufixLocalMasc.length) | 0];
    nomeLocalMasc = prefixLocalMasc + " " + sufixLocalMasc;

    prefixLocalFem = listaPrefixLocalFem[(Math.random() * listaPrefixLocalFem.length) | 0];
    sufixLocalFem = listaSufixLocalFem[(Math.random() * listaSufixLocalFem.length) | 0];
    nomeLocalFem = prefixLocalFem + " " + sufixLocalFem;

    listaNomeLocal = [nomeLocalMasc, nomeLocalFem];
    nomeLocal = listaNomeLocal[(Math.random() * listaNomeLocal.length) | 0];

    // Raça
    listaRaca = ["Aesir","Aesir","Humano","Anão","Anão","Humano","Fira","Fira","Humano","Levent","Levent","Humano","Tailox","Tailox","Humano","Mahok","Mahok","Humano","Elfo","Elfo","Humano","Juban","Juban","Humano","Fauno","Fauno","Humano","Faen","Faen","Humano","Astério Parbani","Astério Parbani","Humano","Astério Arkanita","Astério Arkanita","Humano","Draconiano","Draconiano","Humano","Duplicante","Duplicante","Humano","Gárgula","Gárgula","Humano","Centauro","Centauro","Humano","Metadílio","Metadílio","Humano","Gnoll","Gnoll","Humano","Hamelin","Hamelin","Humano","Naga","Naga","Humano","Orc das Terras Secas","Orc das Terras Secas","Humano","Groton","Groton","Humano","Tritão","Tritão","Humano","Goblin","Goblin","Humano"]
    raca = listaRaca[(Math.random() * listaRaca.length) | 0];

    // Gera a descrição
    modeloDesc1 = "O personagem é um(a) " + raca + " que nasceu em " + local + " chamado(a) " + nomeLocal;
    modeloDesc2 = "Este personagem nasceu em " + local + " conhecido(a) como " + nomeLocal;
    
    //modeloDesc2 = "Em " + local + " com o nome " + nomeLocal + " nasceu...";

    listaModeloDesc = [modeloDesc1, modeloDesc2];
    descricao = listaModeloDesc[(Math.random() * listaModeloDesc.length) | 0];

    document.getElementById("descricao").innerHTML = descricao;
}